### ISSUE TITLE
reverse_iterator 解引用操作符返回局部变量的引用

### ISSUE THREAD

**Issue by jie235** [Alinshans/MyTinySTL#101]
请问 反向迭代器的 operator* 操作符重载是不是错了呀？返回了一个局部变量的引用？

![Capture](https://user-images.githubusercontent.com/38351267/154691811-f76c14a2-d76e-4e73-970d-d5ee14799d08.PNG)

**Comment by Alinshans** [comment]
感谢提问，如上解释~
