### ISSUE TITLE
vector.h中329行重载=的问题

### ISSUE THREAD

**Issue by CodeSniperYang** [Alinshans/MyTinySTL#102]
问一下//原空间较小则新建一个vector，然后复制里面的内容到新空间。但是为什么原空间不要在此时释放呢？是要等到程序运行结束，调用析构函数的时候释放吗

**Comment by Alinshans** [comment]
@CodeSniperYang  
```
vector tmp(rhs.begin(), rhs.end());
swap(tmp);
```
和局部变量swap了，局部变量会在函数结束时析构，释放内存
