### ISSUE TITLE
`test.h` defines reserved macros like `_S`

### ISSUE THREAD

**Issue by StephanTLavavej** [Alinshans/MyTinySTL#107]
I work on MSVC's C++ Standard Library implementation, and we regularly build open-source projects like MyTinySTL in order to prevent compiler and library bugs that would affect such projects. This also allows us to provide advance notice of source-breaking changes.

After merging https://github.com/microsoft/STL/pull/2998 , we found compiler errors when building MyTinySTL. This is ultimately caused by:

https://github.com/Alinshans/MyTinySTL/blob/3441980d89705e10c1cc521625d1a2e6cb1490a0/Test/test.h#L515-L521

These macros are `_Leading_underscore_capital`. Such identifiers are reserved by the C++ Standard for use by the compiler and standard library. One of the headers that the C++ Standard Library drags in, `<mmintrin.h>`, contains intrinsic declarations like

```cpp
__m64 _mm_set1_pi16(short _S);
```

After preprocessing, this becomes `__m64 _mm_set1_pi16(short / 5);` which can't compile. (The `_Leading_underscore_capital` rule exists to prevent the standard library from conflicting with other code like this.)

This has always been a conformance issue, but it appears that we're seeing it now because https://github.com/microsoft/STL/pull/2998 causes `<mmintrin.h>` to be included later than it previously was, after `test.h` has defined `_S`.

To avoid this problem, all of these these test macros should be renamed to avoid the reserved patterns specified by [N4910](https://isocpp.org/files/papers/N4910.pdf) 5.10 [[lex.name]/3](https://eel.is/c++draft/lex.name#3).

**Comment by Adeshen** [comment]
已经收到您的邮件！！！

**Comment by frederick-vs-ja** [comment]
Translated to Chinese (Chinese developers that are not familiar to English should also know this):

> 我从事于 MSVC 的 C++ 标准库实现，而且我们日常地构建 MyTinySTL 这样的开源项目，以避免编译器和标准库的漏洞影响这些项目。这也使我们可以为破坏源码的更改提供更进一步的提醒。
> 
> 在合并 microsoft/STL#2998 后，我们在构建 MyTinySTL 时找到了编译错误。这最终源于：
> 
> https://github.com/Alinshans/MyTinySTL/blob/3441980d89705e10c1cc521625d1a2e6cb1490a0/Test/test.h#L515-L521
> 这些宏为 `_Leading_underscore_capital` （前导下划线大写格式）。 C++ 标准为编译器与标准库的使用保留这些标识符。 C++ 标准库拖进来的头文件之一 `<mmintrin.h>` 含有类似下面的内建子程序声明
> 
> ```c++
> __m64 _mm_set1_pi16(short _S);
> ```
> 
> 在预处理后，这成了编译不了的 `__m64 _mm_set1_pi16(short / 5);` （`_Leading_underscore_capital` 规则的存在避免标准库与这种代码冲突。）
> 
> 这始终有遵从性问题，但看起来是因为 microsoft/STL#2998 导致包含 `<mmintrin.h>` 比先前更迟，在 `test.h` 定义 `_S` 之后，我们才发现它。
> 
> 为避免此问题，所有这些测试宏都应该改名，以避免 [N4910](https://isocpp.org/files/papers/N4910.pdf) 5.10 [[lex.name]/3](https://eel.is/c++draft/lex.name#3) 所指定的保留模式。

I hope I can fix this myself soon.
我希望我能尽快修复此问题。

**Comment by Alinshans** [comment]
Oh!!!! In fact, I am clear about this problem, but the code was written when I was a student, and I didn't understand it at that time. Sorry！ >_<
这个其实我知道，但是代码是太久之前写的了，学生时代不懂事，见笑了。。
