### ISSUE TITLE
关于unorderset_set的比较操作符

### ISSUE THREAD

**Issue by wz1114841863** [Alinshans/MyTinySTL#130]
这里为什么用了equal_range_multi函数，这个函数是用来查键值出来出现的迭代器区间，但hashtable本身并没有实现==，是否应该使用迭代器去逐元素比较
`
  friend bool operator==(const unordered_multiset &lhs, const unordered_multiset &rhs) {
      return lhs.ht_.equal_range_multi(rhs.ht_);
  }
`

**Comment by Adeshen** [comment]
已经收到您的邮件！！！

**Comment by myc13381** [comment]
同问，不知这是为何
