### ISSUE TITLE
address_of不能获取对象的真实地址

### ISSUE THREAD

**Issue by zgjsxx** [Alinshans/MyTinySTL#133]
// 获取对象地址
```cpp
template <class Tp>
constexpr Tp* address_of(Tp& value) noexcept
{
  return &value;
}
```
上述代码用于获取对象的真实地址，但是在重载operator&时，上述代码是不work的，下面是我的一个验证：

https://godbolt.org/z/cPd1WMx7h

可能需要使用```std::addressof```进行修复

**Comment by Adeshen** [comment]
已经收到您的邮件！！！

**Comment by Alinshans** [comment]
确实是这样，所以标准库是比较复杂的，但我这项目不探究完整的实现，旨在建立一个基本的认识，谢谢你提出的问题

**Comment by Adeshen** [comment]
已经收到您的邮件！！！

**Comment by zgjsxx** [comment]
感谢作者回复

**Comment by frederick-vs-ja** [comment]
这个问题不该关，我要修复。
