### ISSUE TITLE
你这里面的alloc.h 里面  有很大错误, 不建议阅读整个项目了.

### ISSUE THREAD

**Issue by zhangbo2008** [Alinshans/MyTinySTL#145]
void alloc::deallocate(void *p, size_t n)
    {
        // 大于 128 bytes 就调用 free
        if (n > static_cast<size_t>(EMaxBytes))
        {
            std::free(p);
            return;
        }
        FreeList *q = static_cast<FreeList *>(p); // p小于128,说明他存在我们的内存池中,找到他的链表地址q
        FreeList *my_free_list;
        my_free_list = free_list[freelist_index(n)]; // 找到对应的自由链表, 把q插入到my_free_list即可.就表示他已经释放了.
        q->next = my_free_list;                      // 将空间回收到内存池 , 头插入.
        my_free_list = q;
    }

这个代码错误, 指针数组完全没修改!!!!!!!!!!!!!!!

**Comment by Peas-Li** [comment]
可以问一下为什么没修改吗，free_list里存的不就是当前链表的指针吗

**Comment by zhangbo2008** [comment]
代码逻辑严重不对，不建议看了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月15日 09:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Alinshans/MyTinySTL] 你这里面的alloc.h 里面  有很大错误, 不建议阅读整个项目了. (Issue #145) |

可以问一下为什么没修改吗，free_list里存的不就是当前链表的指针吗

**Comment by Peas-Li** [comment]
我现在想知道指针数组为啥没修改，谢谢你

**Comment by zhangbo2008** [comment]
不容易说清楚，我很久不看这个代码了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月15日 09:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Alinshans/MyTinySTL] 你这里面的alloc.h 里面  有很大错误, 不建议阅读整个项目了. (Issue #145) |

我现在想知道指针数组为啥没修改，谢谢你
