### ISSUE TITLE
allocator 都不支持的还说支持 c++11 ？

### ISSUE THREAD

**Issue by lhmouse** [Alinshans/MyTinySTL#57]
https://github.com/Alinshans/MyTinySTL/blob/62ef9ef4a4f20001a1136ebc01d52d8558f3d6d8/MyTinySTL/vector.h#L378

**Comment by lhmouse** [comment]
正确使用姿势：

https://github.com/lhmouse/asteria/blob/b1f9c01b9b2c6780ee16bd7b0eed7c9e30aeeb3a/asteria/src/rocket/cow_vector.hpp#L397

**Comment by shrinktofit** [comment]
.....兄弟好凶

**Comment by XUEBOKIVI** [comment]
你在说什么？

**Comment by ksxh0524** [comment]
哪来的13

**Comment by frederick-vs-ja** [comment]
问题不只在这一行。
这个库的容器分配器等于只有 `mystl::allocator` 一种，其存在的意义基本只有留待用户特化了。

**Comment by hasakilol** [comment]
说话怎么戾气这么大？ 作为一个人的素质在哪里？ 我感觉中国的程序员本事不大，吹牛第一。我之前遇到一个写blog的闲人，他说他随便就能写一个vue，然后我问他怎么写，他说就参考vue的实现。我就问他，那是人家写好了，我问的是你，如果没有vue，没有react，你怎么写？ 人家坚持说很简单。

**Comment by Alinshans** [comment]
@hasakilol  他是我认识的大佬QwQ  这个也只是大一大二写的玩具 也就是练习一下打码速度  大佬友情帮我review我已经很开心了！大家不要误会 quq  他没有恶意的~！ =v=

**Comment by lhmouse** [comment]
@Alinshans 来给欧尼酱摸摸头~

**Comment by Alinshans** [comment]
大家看到不用觉得这是在喷 我和lhmouse大佬私下也是好朋友  男人嘛~说话直来直去很正常 毕竟当时嫌麻烦很多复杂的东西都没实现=。=  大家别介意别误会吼

**Comment by Alinshans** [comment]
@lhmouse 喵喵欧乃桑！

**Comment by FrankHB** [comment]
> 大家看到不用觉得这是在喷 我和lhmouse大佬私下也是好朋友 男人嘛~说话直来直去很正常 毕竟当时嫌麻烦很多复杂的东西都没实现=。= 大家别介意别误会吼

这是越描越黑……一眼就看成了**男朋友**。

**Comment by hasakilol** [comment]
> @hasakilol 他是我认识的大佬QwQ 这个也只是大一大二写的玩具 也就是练习一下打码速度 大佬友情帮我review我已经很开心了！大家不要误会 quq 他没有恶意的~！ =v=

没有恶意，就可以骂人了？ 我觉得有点说不通。

**Comment by FrankHB** [comment]
Suggesting NAD.

The title indicates it is "in C++11", not implying conforming to C++11.

The name "STL" is ambiguous. It is not necessary the standard library (albeit there exist some bad examples [like this](https://devblogs.microsoft.com/cppblog/open-sourcing-msvcs-stl/#comment-467)), so technically there is nothing to conform.

(Also note that container templates like `std::array` are intentionally not allocator-aware.)

**Comment by FrankHB** [comment]
@hasakilol 注意你的言辞。至少我没看见先前谁有在骂“人”。

倒是你说的：

> 作为一个人的素质在哪里？ 我感觉中国的程序员本事不大，吹牛第一。

涉嫌[人身批评](https://zh.wikipedia.org/zh-cn/%E8%A8%B4%E8%AB%B8%E4%BA%BA%E8%BA%AB)，技术上看起来更接近你所谓的“骂人”。

**Comment by hasakilol** [comment]
> @hasakilol 注意你的言辞。至少我没看见先前谁有在骂“人”。
> 
> 倒是你说的：
> 
> > 作为一个人的素质在哪里？ 我感觉中国的程序员本事不大，吹牛第一。
> 
> 涉嫌[人身批评](https://zh.wikipedia.org/zh-cn/%E8%A8%B4%E8%AB%B8%E4%BA%BA%E8%BA%AB)，技术上看起来更接近你所谓的“骂人”。

"碧莲" ????????????????????   你是选择性无视吗？  我的言辞有什么问题？ 你要是找不出来我的言辞有什么问题，你就给我跪下道歉，行不行？

**Comment by FrankHB** [comment]
@hasakilol

> "碧莲" ????????????????????

“碧莲”咋了？是不是觉得但凡您在乎看起来爽不爽快的，您以外就不得商榷有还是没有了？

再者，标题本就没指着你脸说，没放地图炮误伤贵体，和您贵干？合着就只准您发正义春指点江山了？

对了，啧啧，“中国的程序员”是谁说的来着？

> 你是选择性无视吗？

选择性无视啥？隔俩礼拜诈尸，这点都憋不清楚嘛？

您是想让人脑补，您自个儿的问题和别人的问题其实是一回事，有谁在双标还是咋地？啧啧，先不说你这附会得不着边际的本事，是不是要特别再提点您一下：不要用心险恶得太低级太明显？

对了，啧啧啧，“中国的程序员”是谁说的来着？

> 我的言辞有什么问题？你要是找不出来我的言辞有什么问题，你就给我跪下道歉，行不行？

精确到句的原文引用和参考链接都给了，真不晓得怎么对号入座？还是根本看不懂中文？要么就再给你一个帽子：伸手党，接好，跪下。

对了，啧啧啧啧，“中国的程序员”是谁说的来着？

**Comment by kid-own-code** [comment]
喜欢吵吵的人什么水平大家心里都清楚，丢人现眼哟

**Comment by crazii** [comment]
碧莲? 大家我, 我是许仕林, 我已经不要碧莲了 (狗头)

**Comment by NFWSA** [comment]
碧莲? 大家我, 我是渣渣辉， 我已经不要碧莲了 (狗头)

**Comment by notfresh** [comment]
不想看上面的评论撕逼了，就算是朋友， 在大庭广众下发这种标题，建议整改一下，@lhmouse  @Alinshans
有些朋友之间的话就不能私下说吗？

**Comment by dengyunsheng250** [comment]
这issue。。。。
