### ISSUE TITLE
vector的reinsert函数可能需要归还原先开辟的内存

### ISSUE THREAD

**Issue by Hongjingdong** [Alinshans/MyTinySTL#62]
原函数为
// reinsert 函数
template <class T>
void vector<T>::reinsert(size_type size)
{
  auto new_begin = data_allocator::allocate(size);
  try
  {
    mystl::uninitialized_move(begin_, end_, new_begin);
  }
  catch (...)
  {
    data_allocator::deallocate(new_begin, size);
    throw;
  }
  begin_ = new_begin;
  end_ = begin_ + size;
  cap_ = begin_ + size;
}
应该在move后归还原begin_开辟的内存。即：
// reinsert 函数
template <class T>
void vector<T>::reinsert(size_type size)
{
  auto new_begin = data_allocator::allocate(size);
  try
  {
    mystl::uninitialized_move(begin_, end_, new_begin);
  }
  catch (...)
  {
    data_allocator::deallocate(new_begin, size);
    throw;
  }
  data_allocator::deallocate(begin_, cap_ - begin_);//我觉得这应该不上这个语句，归还内存。
  begin_ = new_begin;
  end_ = begin_ + size;
  cap_ = begin_ + size;
}

**Comment by Alinshans** [comment]
@Hongjingdong 应该要加上，感谢提醒！
