### ISSUE TITLE
alog.h

### ISSUE THREAD

**Issue by zxpgo** [Alinshans/MyTinySTL#65]
![image](https://user-images.githubusercontent.com/37869997/63649884-e3e44600-c775-11e9-977e-14b8034f8309.png)
upper_bound函数是得到最后一个大于或等于value的迭代器，但是在这个函数(erange_dispatch)里面是要等于value吧，不能大于

**Comment by Alinshans** [comment]
@zxpgo 
不是，upper_bound 是得到第一个大于value的迭代器，equal_range 的返回值，第一个就是第一个不小于value的元素，第二个是第一个大于value的元素，分别对应lower_bound和upper_bound。
https://en.cppreference.com/w/cpp/algorithm/upper_bound
https://en.cppreference.com/w/cpp/algorithm/equal_range

**Comment by zxpgo** [comment]
![image](https://user-images.githubusercontent.com/37869997/63772887-a4039700-c90c-11e9-8e9a-968378c3174d.png)

那这个地方写错了吧，最后一个不小于value就是最后一个大于等于value的位置，里面包含了等于。而且最后一个会被理解错为最后一个大于等于value的值。

**Comment by Alinshans** [comment]
@zxpgo 
emm 是的，以前可能没理解清楚写错了... 感谢指出 你可以提个PR或者我等会改
