### ISSUE TITLE
questions regarding to RUN_ALL_TESTS

### ISSUE THREAD

**Issue by jimailster** [Alinshans/MyTinySTL#68]
Hi Alinshans,

Thanks for share such a good project. I have a question regarding to the RUN_ALL_TESTS.

I can't figure out how the test cases are created and registered. I just see a TestCase constructor takes one parameter, but the UnitTest GetInstance will use TestCase's default constructor, there is no parameter to initialize testcase_name. Also, I don't see where the RegisterTestCase get called.

I am looking forward to your answer. Thanks in advance.

Jimailster

**Comment by jimailster** [comment]
Alright, I figured out. It magic is in the xxxx_test.h. beautiful!

**Comment by Alinshans** [comment]
@jimailster 

Yes, the key is the macro in https://github.com/Alinshans/MyTinySTL/blob/master/Test/test.h#L127 , and I define another macon named `TEST` to call `MYTINYSTL_TEST` in line 697, so when you use `TEST(xxx){}` you register a testcase, and implemented the `run` function, this macro is mainly to test some algorithm functions that you can find in `algorithm_test.h`.

It seems you have read the code very carefully, I appreciate someone doing this!

**Comment by jimailster** [comment]
Hi Alinshans,

Thank you for depicting the details. I believe it is helpful for other readers as well.

Jimailster
