### ISSUE TITLE
代码的复用

### ISSUE THREAD

**Issue by pagict** [Alinshans/MyTinySTL#69]
代码的复用程度不够。
比如
https://github.com/Alinshans/MyTinySTL/blob/a04c83108a2ae2c6fed6942dd0fd842096bff76b/MyTinySTL/algo.h#L141-L145 和 https://github.com/Alinshans/MyTinySTL/blob/a04c83108a2ae2c6fed6942dd0fd842096bff76b/MyTinySTL/algo.h#L177-L181 的实现绝大部分都一致，应该是 `search4` 调用 `search5` 才对，而不是重新再实现一遍。

**Comment by Alinshans** [comment]
是的，其实实现的时候只需要给 Compared 一个默认的参数就行，不过都是以前写的了，后面的朋友注意一下就好
