### ISSUE TITLE
alloc.h

### ISSUE THREAD

**Issue by zhangyi4399** [Alinshans/MyTinySTL#73]
![image](https://user-images.githubusercontent.com/25844240/94355746-4ca89b00-00b9-11eb-9342-3d9054e17dd7.png)
这样好像并不能改变链表数组的值吧，还是我看错了？类似的问题这个文件里还有一些，M_refill，M_chunk_alloc可能都有

**Comment by arcral** [comment]
是写错了，应该用二级指针修改

**Comment by Alinshans** [comment]
是写错了，这个文件很早前写的，后面已经不用了，就没去改，还是你们看得仔细
