### ISSUE TITLE
第二个deallocate函数的作用

### ISSUE THREAD

**Issue by Mr-Second** [Alinshans/MyTinySTL#74]
`template <class T>`
`void allocator<T>::deallocate(T* ptr)`
`{`
`  if (ptr == nullptr)`
`    return;`
`  ::operator delete(ptr);`
`}`

`template <class T>`
`void allocator<T>::deallocate(T* ptr, size_type /*size*/)`
`{`
`  if (ptr == nullptr)`
`    return;`
`  ::operator delete(ptr);`
`}`
第二个函数为啥要注释size？本意是用来析构T数组的嘛，那为啥不用
`operator delete[] (ptr)`？
本人菜鸟一只，希望得到解答

**Comment by Alinshans** [comment]
就是接口上提供了多一种方法，但实际上delete不需要把长度显式传递过去，它自己会知道长度，所以实际不需要size的参数，也没啥特别的用途
