### ISSUE TITLE
vector.h 中 explicit vector 构造函数中 value_type() 的迷惑

### ISSUE THREAD

**Issue by Misng** [Alinshans/MyTinySTL#99]
```cpp
 explicit vector(size_type n)
  { fill_init(n, value_type()); }
```
为什么value_type 后面要添加() , 我猜测这个是函数吧。它的原型是 `mystl::allocator<T>::value_type()` 吗？ 可我在 allocator 中没有找到对应函数的实现呀

**Comment by Adeshen** [comment]
已经收到您的邮件！！！

**Comment by v1nh1shungry** [comment]
并不是函数，而是构造一个纯右值，请仔细看`value_type`是一个类型别名，举个例子，`vector<int>`里的`value_type`就是`int`，那么这里就是`fill_init(n, int())`了。

**Comment by Misng** [comment]
> 并不是函数，而是构造一个纯右值，请仔细看`value_type`是一个类型别名，举个例子，`vector<int>`里的`value_type`就是`int`，那么这里就是`fill_init(n, int())`了。

多谢
